name: AspNetCore.Identity.Stores-PR

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - AspNetCore.Identity.Stores/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore AspNetCore.Identity.Stores/AspNetCore.Identity.Stores.sln
    - name: Build
      run: dotnet build --no-restore AspNetCore.Identity.Stores/AspNetCore.Identity.Stores.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal AspNetCore.Identity.Stores/AspNetCore.Identity.Stores.sln
