name: AspNetCore.Identity.Stores-publish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore AspNetCore.Identity.Stores/AspNetCore.Identity.Stores
    - name: Build
      run: dotnet build --no-restore AspNetCore.Identity.Stores/AspNetCore.Identity.Stores
    - name: Test
      run: dotnet test --no-build --verbosity normal AspNetCore.Identity.Stores/AspNetCore.Identity.Stores
    - name: Publish AspNetCore.Identity.Stores.AzureStorageAccount
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: AspNetCore.Identity.Stores/AspNetCore.Identity.Stores.AzureStorageAccount/AspNetCore.Identity.Stores.AzureStorageAccount.csproj
          NUGET_KEY: ${{secrets.NUGET}}
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>$
